In [2]:
print("hello")

hello


In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]
type(mylist)

list

In [5]:
# create Array
np.array(mylist)

array([1, 2, 3])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
# Create array with Zeros
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.random.seed(5)

In [10]:
arr = np.random.randint(0,10,2)

In [11]:
arr

array([3, 6])

In [14]:
#returns Max
arr.max()

6

In [13]:
# returns Index Location
arr.argmax()

1

In [15]:
#returns min
arr.min()

#returns index
arr.argmin()

0

In [16]:
#mean
arr.mean()

4.5

In [17]:
arr.shape()

TypeError: 'tuple' object is not callable

In [18]:
arr.shape

(2,)

In [19]:
arr.reshape(2,1)

array([[3],
       [6]])

In [20]:
#error because of only 2 elements
arr.reshape(2,10)

ValueError: cannot reshape array of size 2 into shape (2,10)

In [21]:
mat = np.arange(0,100).reshape(10,10)

In [22]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
type (mat)

numpy.ndarray

In [24]:
mat.shape

(10, 10)

In [25]:
#get Index Value
row = 2
col = 5
mat[row,col]

25

In [26]:
#get column values; : for all values
mat[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [28]:
#by rows
mat[:,3].reshape(10,1)

array([[ 3],
       [13],
       [23],
       [33],
       [43],
       [53],
       [63],
       [73],
       [83],
       [93]])

In [29]:
#get row values;
mat[6,:]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [30]:
mar[0:4, 0:4]

NameError: name 'mar' is not defined

In [31]:
# get rows 0to4 and cols 0to4
mat[0:4, 0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [32]:
# reinitialies to diff value
mat[0:2,0:3] = 7

In [33]:
mat

array([[ 7,  7,  7,  3,  4,  5,  6,  7,  8,  9],
       [ 7,  7,  7, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])